### ISSUE TITLE
Communicate with Trie Team about Trie Structure / Visualizations

### ISSUE THREAD

**Issue by mkai5** [cmsc22000-project-2018/support-tools#26]
5.9 - Elizabeth and I had some lingering questions and doubts about the Trie team's data structure, so we want to reach out and talk to them about their data structure and working with the API recursively.

5.14 - Just met with trie team before class to communicate that the visualizations would have to be implemented server-side. (Reached out to Trie team on Tuesday and Thursday in the general chat without reply. Reached out directly through their channel on Friday, received a reply on Sunday afternoon, when we set up a meeting before class).

**Comment by borjasotomayor** [comment]
Could you expand on what you mean by "working with the API recursively"? I continue to be concerned that this means you're thinking about the Trie API in the wrong way. It should not be your job to recurse through a Trie; if an operation requires recursion, it should be done by the Trie team, and you should receive the results of that operation through the API.

**Comment by borjasotomayor** [comment]
I believe you may have misheard me: what I said is that you could certainly give your recursive functions to the tries team or the APIs team to provide them with guidance on what you need (I may have said that it's unlikely they'd be able to just directly reuse your code). In this class, it is never inappropriate to share code with other teams.

I think a point of confusion may be that this is _not_ a recursive vs iterative issue; this is about what belongs in the tries/API and what belongs in your code. Instead of thinking about "how do I traverse this data structure that lives off in a server" you should think in terms of how to get the data you need with the least number of API calls (take into account that API calls will be expensive: they involve going over the network to a server to get information about a data structure).

Let me give you a simple example with a binary search tree. Let's say we have this tree:

```
     10
   /    \
  7     20
 / \   /  \
 1 9   15 27
```

Doing an inorder traversal of this tree is simple if the tree lives in memory:

```
inorder(t)
{
    inorder(t.left)
    print(t.value)
    inorder(t.right)
}
```

(for simplicity, let's assume that accessing t.value when t is NULL doesn't result in an error, it just results in nothing being printed out)

When you think about doing this through an API, things can get tricky:

```
inorder(t)
{
    left_tree = tree_api_get_left(t)
    inorder(left_tree)
    value = tree_api_get_value(t)
    print(t.value)
    right_tree = tree_api_get_right(t)
    inorder(right_tree)
}
```

This means you're making three API calls per node. If your tree has 10,000 nodes, that's 30,000 API calls over the network to do what is a very simple traversal. Even if you optimistically assume you're on a local network and that a single API call takes 1 millisecond, that still means it will take you 30 seconds to traverse the tree (and even if the API provides the ability to return the left subtree, right subtree, and value in a single API call, it still takes 10 seconds to traverse the whole tree). If the API calls happen over the Internet, the per-call time could be in the order of 10ms (so, 100 seconds to traverse the entire tree).

This suggest that this traversal should simply be done in the server, and the API should provide you with ways to obtain the _result_ of that traversal. For example, the API could provide a function like this:

```
/*
  traversal() -- Traverses a tree and returns a list of values in the traversal order

  Parameters:
    - order: 0 (inorder), 1 (preorder), or 2 (postorder)
    - threshold: (int) Do not return anything if more than "threshold" values would 
                       be returned. Use 0 to indicate unlimited values.
    - result: (list of values) Output parameter with the list of values.

  Return value:
   - 0: success
   - 1: number of values would exceed threshold
*/
int traversal(...);
```

With this function, a traversal can be accomplished with just a single API call. Please note that I'm not suggesting that the API team should implement a function exactly like the one above but with tries. This is meant to highlight that you should not be thinking in terms of accessing a trie node by node (except when absolutely necessary).

**Comment by ecrowdus** [comment]
@borjasotomayor thanks so much for the clarification. @mkai5 and I just touched base about it and we are going to reschedule a meeting with @AKAlilonu with this framework in mind.

**Comment by mkai5** [comment]
@borjasotomayor  Thanks for your clarification! We will also meet thoroughly with the trie team in order to talk about taking our implementations and adopting them to their end of the platform, accessible through the API.
